import React,{useEffect,useMemo,useRef,useState}from'react';

type Region={id:string;imageId:string;x:number;y:number;w:number;h:number;label:string;fillColor?:string;borderColor?:string;opacity?:number};
type Img={id:string;blob:Blob;w:number;h:number;name:string};
type Card={id:string;imageId:string;regions:string[];deck:string;tags:string[];due:number;reps:number;lapses:number;interval:number;ease:number};
type Point={x:number;y:number};
type Annotation={id:string;imageId:string;type:'text'|'pen'|'image';x:number;y:number;w:number;h:number;text?:string;points?:Point[];blob?:Blob;color?:string};

const DB='recallforge-v1',V=2;let dbp:Promise<IDBDatabase>|null=null;
function db(){if(dbp)return dbp;dbp=new Promise((res,rej)=>{const r=indexedDB.open(DB,V);r.onupgradeneeded=()=>{const d=r.result;for(const n of['images','regions','cards','annotations'])if(!d.objectStoreNames.contains(n))d.createObjectStore(n,{keyPath:'id'});};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});return dbp}
async function all<T>(s:string){const d=await db(),t=d.transaction(s,'readonly').objectStore(s);return new Promise<T[]>((res,rej)=>{const r=t.getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function put(s:string,v:any){const d=await db();return new Promise<void>((res,rej)=>{const r=d.transaction(s,'readwrite').objectStore(s).put(v);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function del(s:string,id:string){const d=await db();d.transaction(s,'readwrite').objectStore(s).delete(id)}
const uid=()=>crypto.randomUUID(),now=()=>Date.now(),blobUrl=(b?:Blob)=>b?URL.createObjectURL(b):'';

function ImageThumb({image,onOpen}:{image:Img;onOpen:()=>void}){const[u,setU]=useState('');useEffect(()=>{const x=blobUrl(image.blob);setU(x);return()=>URL.revokeObjectURL(x)},[image]);return <div className="imageCard"><img src={u} alt={image.name}/><div className="imageMeta"><b title={image.name}>{image.name}</b><small>{image.w} × {image.h}px</small><button onClick={onOpen}>Edit</button></div></div>}

function App(){
 const[tab,setTab]=useState('Dashboard'),[images,setImages]=useState<Img[]>([]),[regions,setRegions]=useState<Region[]>([]),[annotations,setAnnotations]=useState<Annotation[]>([]),[cards,setCards]=useState<Card[]>([]),[deck,setDeck]=useState('Default'),[selected,setSelected]=useState<string[]>([]),[editing,setEditing]=useState<Img|null>(null),[editingUrl,setEditingUrl]=useState(''),[studyUrl,setStudyUrl]=useState(''),[hidden,setHidden]=useState(true),[idx,setIdx]=useState(0),[reviewAll,setReviewAll]=useState(false),[message,setMessage]=useState(''),[tool,setTool]=useState<'select'|'region'|'pen'|'text'|'image'|'eraser'>('select'),[penColor,setPenColor]=useState('#2563eb'),[occlusionFill,setOcclusionFill]=useState('#111827'),[occlusionBorder,setOcclusionBorder]=useState('#ef4444'),[occlusionOpacity,setOcclusionOpacity]=useState(.72),[textDraft,setTextDraft]=useState<{x:number;y:number;value:string}|null>(null),[drag,setDrag]=useState<{kind:'region'|'annotation';id:string;mode:'move'|'resize';startX:number;startY:number;start:{x:number;y:number;w:number;h:number}}|null>(null),[drawing,setDrawing]=useState<Point[]>([]),[regionDraft,setRegionDraft]=useState<{x:number;y:number;w:number;h:number}|null>(null);
 const fileRef=useRef<HTMLInputElement>(null),overlayRef=useRef<HTMLInputElement>(null),canvasRef=useRef<HTMLDivElement>(null);
 async function refresh(){setImages(await all<Img>('images'));setRegions(await all<Region>('regions'));setAnnotations(await all<Annotation>('annotations'));setCards(await all<Card>('cards'))}
 useEffect(()=>{refresh()},[]);
 const due=useMemo(()=>cards.filter(c=>c.due<=now()),[cards]),queue=reviewAll?cards:due,card=queue.length?queue[idx%queue.length]:undefined,studyImg=card?images.find(x=>x.id===card.imageId):undefined;
 useEffect(()=>{if(!editing){setEditingUrl('');return}const u=blobUrl(editing.blob);setEditingUrl(u);return()=>URL.revokeObjectURL(u)},[editing]);
 useEffect(()=>{if(!studyImg){setStudyUrl('');return}const u=blobUrl(studyImg.blob);setStudyUrl(u);return()=>URL.revokeObjectURL(u)},[studyImg]);

 function localPoint(e:React.PointerEvent|React.MouseEvent){const el=canvasRef.current;if(!el)return{x:0,y:0};const r=el.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))}}
 async function readImageSize(file:File){const url=URL.createObjectURL(file);try{const im=new Image();im.src=url;await new Promise<void>((resolve,reject)=>{im.onload=()=>resolve();im.onerror=()=>reject(new Error('This image format could not be decoded by the browser.'))});return{w:im.naturalWidth,h:im.naturalHeight}}finally{URL.revokeObjectURL(url)}}
 async function upload(f:File){try{if(!f)return;if(!f.type.startsWith('image/')&&!/\\.(png|jpe?g|gif|webp|bmp|svg|avif|heic|heif)$/i.test(f.name)){setMessage('Please select an image file.');return}const size=await readImageSize(f);const blob=new Blob([await f.arrayBuffer()],{type:f.type||'application/octet-stream'});const x:Img={id:uid(),blob,w:size.w,h:size.h,name:f.name};await put('images',x);await refresh();setEditing(x);setSelected([]);setTool('select');setTab('Editor');setMessage('Image uploaded — all editing tools are ready.')}catch(err){console.error(err);setMessage(err instanceof Error?err.message:'Could not upload the image. Please try another image.')}}
 function openImage(i:Img){setEditing(i);setSelected([]);setTool('select');setTab('Editor')}
 function openImages(){setEditing(null);setSelected([]);setTab('Editor')}
 async function addRegionAt(x=.2,y=.2,w=.25,h=.12){if(!editing)return;const r:Region={id:uid(),imageId:editing.id,x,y,w,h,label:'',fillColor:occlusionFill,borderColor:occlusionBorder,opacity:occlusionOpacity};await put('regions',r);setRegions(v=>[...v,r]);setSelected([r.id]);setTool('select')}
 function beginRegionDraw(e:React.PointerEvent){if(tool!=='region'||!editing||e.detail!==2)return;const p=localPoint(e);setRegionDraft({x:p.x,y:p.y,w:0,h:0});e.currentTarget.setPointerCapture(e.pointerId);e.preventDefault()}
 function updateRegionDraft(e:React.PointerEvent){if(!regionDraft)return;const p=localPoint(e),x=Math.min(regionDraft.x,p.x),y=Math.min(regionDraft.y,p.y),w=Math.abs(p.x-regionDraft.x),h=Math.abs(p.y-regionDraft.y);setRegionDraft({x,y,w,h})}
 async function finishRegionDraw(){if(!regionDraft||!editing){setRegionDraft(null);return}if(regionDraft.w<.01||regionDraft.h<.01){setRegionDraft(null);return}const r:Region={id:uid(),imageId:editing.id,x:regionDraft.x,y:regionDraft.y,w:regionDraft.w,h:regionDraft.h,label:'',fillColor:occlusionFill,borderColor:occlusionBorder,opacity:occlusionOpacity};await put('regions',r);setRegions(v=>[...v,r]);setSelected([r.id]);setRegionDraft(null);setTool('select')}
 function beginDrag(e:React.PointerEvent,id:string,mode:'move'|'resize'){e.stopPropagation();e.preventDefault();const p=localPoint(e),r=regions.find(x=>x.id===id);if(!r)return;setSelected([r.id]);setDrag({kind:'region',id,mode,startX:p.x,startY:p.y,start:{x:r.x,y:r.y,w:r.w,h:r.h}});e.currentTarget.setPointerCapture?.(e.pointerId)}
 function beginAnnDrag(e:React.PointerEvent,a:Annotation,mode:'move'|'resize'){e.stopPropagation();e.preventDefault();if(tool==='eraser'){del('annotations',a.id);setAnnotations(v=>v.filter(x=>x.id!==a.id));return}const p=localPoint(e);setDrag({kind:'annotation',id:a.id,mode,startX:p.x,startY:p.y,start:{x:a.x,y:a.y,w:a.w,h:a.h}});e.currentTarget.setPointerCapture?.(e.pointerId)}
 function onPointerMove(e:React.PointerEvent){if(regionDraft){updateRegionDraft(e);return}if(tool==='pen'){if(drawing.length)setDrawing(v=>[...v,localPoint(e)]);return}if(!drag)return;const p=localPoint(e),dx=p.x-drag.startX,dy=p.y-drag.startY;if(drag.kind==='region'){const r=regions.find(x=>x.id===drag.id);if(!r)return;const n:Region=drag.mode==='move'?{...r,x:Math.max(0,Math.min(1-drag.start.w,drag.start.x+dx)),y:Math.max(0,Math.min(1-drag.start.h,drag.start.y+dy))}:{...r,w:Math.max(.02,Math.min(1-drag.start.x,drag.start.w+dx)),h:Math.max(.02,Math.min(1-drag.start.y,drag.start.h+dy))};setRegions(v=>v.map(x=>x.id===r.id?n:x));void put('regions',n)}else{const a=annotations.find(x=>x.id===drag.id);if(!a)return;const n:Annotation=drag.mode==='move'?{...a,x:Math.max(0,Math.min(1-drag.start.w,drag.start.x+dx)),y:Math.max(0,Math.min(1-drag.start.h,drag.start.y+dy))}:{...a,w:Math.max(.03,Math.min(1-drag.start.x,drag.start.w+dx)),h:Math.max(.03,Math.min(1-drag.start.y,drag.start.h+dy))};setAnnotations(v=>v.map(x=>x.id===a.id?n:x));void put('annotations',n)}}
 function endDrag(){setDrag(null)}
 function handleCanvasDown(e:React.PointerEvent){if(!editing)return;if(tool==='region'){return}if(tool==='pen'){setDrawing([localPoint(e)]);e.currentTarget.setPointerCapture(e.pointerId);return}if(tool==='text'){const p=localPoint(e);setTextDraft({x:p.x,y:p.y,value:''});return}if(tool==='eraser'){const p=localPoint(e);const hit=annotations.find(a=>p.x>=a.x-.02&&p.x<=a.x+a.w+.02&&p.y>=a.y-.02&&p.y<=a.y+a.h+.02);if(hit){void del('annotations',hit.id);setAnnotations(v=>v.filter(a=>a.id!==hit.id))}}}
 async function saveText(){if(!editing||!textDraft?.value.trim()){setTextDraft(null);return}const a:Annotation={id:uid(),imageId:editing.id,type:'text',x:textDraft.x,y:textDraft.y,w:.25,h:.08,text:textDraft.value,color:penColor};await put('annotations',a);setAnnotations(v=>[...v,a]);setTextDraft(null);setTool('select')}
 function startPen(e:React.PointerEvent){if(tool!=='pen'||!editing)return;setDrawing([localPoint(e)]);e.currentTarget.setPointerCapture(e.pointerId)}
 async function endPen(){if(!drawing.length||!editing)return;const xs=drawing.map(p=>p.x),ys=drawing.map(p=>p.y),a:Annotation={id:uid(),imageId:editing.id,type:'pen',x:Math.min(...xs),y:Math.min(...ys),w:Math.max(.01,Math.max(...xs)-Math.min(...xs)),h:Math.max(.01,Math.max(...ys)-Math.min(...ys)),points:drawing,color:penColor};await put('annotations',a);setAnnotations(v=>[...v,a]);setDrawing([]);setTool('select')}
 async function addOverlay(f:File){try{if(!editing||!f)return;if(!f.type.startsWith('image/')&&!/\\.(png|jpe?g|gif|webp|bmp|svg|avif|heic|heif)$/i.test(f.name)){setMessage('Please select an image file for the overlay.');return}const blob=new Blob([await f.arrayBuffer()],{type:f.type||'application/octet-stream'});const a:Annotation={id:uid(),imageId:editing.id,type:'image',x:.1,y:.1,w:.35,h:.25,blob,color:penColor};await put('annotations',a);setAnnotations(v=>[...v,a]);setTool('select');setMessage('Overlay image added — drag it or resize it from the corner.')}catch(err){console.error(err);setMessage(err instanceof Error?err.message:'Could not add the overlay image.')}}
 async function saveCards(){if(!editing||!selected.length)return;const c:Card={id:uid(),imageId:editing.id,regions:selected,deck,tags:[],due:now(),reps:0,lapses:0,interval:0,ease:2.5};await put('cards',c);setMessage('Card created');setTab('Dashboard');setIdx(0);setHidden(true);setReviewAll(false);await refresh()}
 async function rate(n:number){if(!card)return;const c={...card,reps:card.reps+1};if(n===1){c.lapses++;c.interval=0;c.ease=Math.max(1.3,c.ease-.2);c.due=now()+60000}else{const mult=n===2?0.7:n===3?c.ease:c.ease+0.25;c.interval=Math.max(1,Math.round((c.interval||1)*mult));c.ease=Math.max(1.3,c.ease+(n===2?-.15:n===4?.15:0));c.due=now()+c.interval*86400000}await put('cards',c);setHidden(true);setIdx(x=>x+1);await refresh()}
 function startStudy(allCards=false){setReviewAll(allCards);setIdx(0);setHidden(true);setTab('Study')}
 async function backup(){const dataUrl=async(b:Blob)=>new Promise<string>((r,j)=>{const x=new FileReader();x.onload=()=>r(String(x.result));x.onerror=()=>j(x.error);x.readAsDataURL(b)});const ims=await Promise.all(images.map(async x=>({...x,blob:await dataUrl(x.blob)})));const anns=await Promise.all(annotations.map(async a=>a.blob?{...a,blob:await dataUrl(a.blob)}:a));const b={version:2,images:ims,regions,annotations:anns,cards};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(b)],{type:'application/json'}));a.download='recallforge-backup.json';a.click()}
 async function restore(f:File){const b=JSON.parse(await f.text());for(const x of b.images){const blob=await(await fetch(x.blob)).blob();await put('images',{...x,blob})}for(const r of b.regions||[])await put('regions',r);for(const a of b.annotations||[]){const blob=a.blob&&typeof a.blob==='string'?await(await fetch(a.blob)).blob():a.blob;await put('annotations',{...a,blob})}for(const c of b.cards)await put('cards',c);await refresh();setMessage('Backup restored')}

 function Editor(){const rs=regions.filter(r=>r.imageId===editing?.id),anns=annotations.filter(a=>a.imageId===editing?.id);if(!editing)return <section><div className="sectionHead"><div><h2>Image Library</h2><p className="muted">Select an image and click Edit to activate all editing tools.</p></div><button onClick={()=>fileRef.current?.click()}>+ Upload Image</button></div>{images.length===0?<p>No images uploaded yet.</p>:<div className="imageGrid">{images.map(i=><ImageThumb key={i.id} image={i} onOpen={()=>openImage(i)}/>)}</div>}</section>;
 return <section><div className="sectionHead"><div><h2>Image Editor</h2><p className="muted">{editing.name} · {editing.w} × {editing.h}px</p></div><div className="toolbar"><button className={tool==='select'?'toolActive':''} onClick={()=>setTool('select')}>Select</button><button className={tool==='region'?'toolActive':''} onClick={()=>{setTool('region');setMessage('Double-click/tap on an empty part of the image, then drag to draw the occlusion at any size. Existing boxes remain draggable and resizable.')}}>+ Occlusion</button><button className={tool==='pen'?'toolActive':''} onClick={()=>setTool('pen')}>Pen</button><button className={tool==='text'?'toolActive':''} onClick={()=>setTool('text')}>Text</button><button className={tool==='eraser'?'toolActive':''} onClick={()=>setTool('eraser')}>Eraser</button><label className="colorPicker">Color <input type="color" value={penColor} onChange={e=>setPenColor(e.target.value)}/></label><button onClick={()=>overlayRef.current?.click()}>+ Image</button><input ref={overlayRef} hidden type="file" accept="image/*,.heic,.heif" onClick={e=>e.stopPropagation()} onChange={e=>{const f=e.currentTarget.files?.[0];e.currentTarget.value='';if(f)addOverlay(f)}}/><button onClick={openImages}>Images</button></div></div>
 <div className="editor"><div ref={canvasRef} className={'canvas editCanvas tool-'+tool} onPointerDown={e=>{handleCanvasDown(e);if(tool==='region'&&e.detail===2)beginRegionDraw(e)}} onDoubleClick={e=>{if(tool==='region'){e.preventDefault()}}} onPointerMove={onPointerMove} onPointerUp={e=>{if(tool==='pen')endPen();else if(regionDraft)void finishRegionDraw();else endDrag()}} onPointerCancel={e=>{if(tool==='pen')setDrawing([]);else endDrag()}}>
  <img src={editingUrl} alt={editing.name}/>
  {rs.map(r=><div key={r.id} className={'mask '+(selected.includes(r.id)?'sel':'')} style={{left:r.x*100+'%',top:r.y*100+'%',width:r.w*100+'%',height:r.h*100+'%',background:r.fillColor||'#111827',borderColor:r.borderColor||'#ef4444',opacity:r.opacity??.72}} onPointerDown={e=>beginDrag(e,r.id,'move')}><span>{r.label||'Region'}</span><i className="resizeHandle" onPointerDown={e=>{e.stopPropagation();e.preventDefault();beginDrag(e,r.id,'resize')}}/></div>)}
  {anns.map(a=>a.type==='text'?<div key={a.id} className="annotation textAnn" style={{left:a.x*100+'%',top:a.y*100+'%',width:a.w*100+'%',height:a.h*100+'%',color:a.color||'#2563eb'}} onPointerDown={e=>beginAnnDrag(e,a,'move')}>{a.text}<i className="resizeHandle" onPointerDown={e=>{e.stopPropagation();e.preventDefault();beginAnnDrag(e,a,'resize')}}/></div>:a.type==='image'?<div key={a.id} className="annotation imageAnn" style={{left:a.x*100+'%',top:a.y*100+'%',width:a.w*100+'%',height:a.h*100+'%'}} onPointerDown={e=>beginAnnDrag(e,a,'move')}><img src={blobUrl(a.blob)} alt="Overlay"/><i className="resizeHandle" onPointerDown={e=>{e.stopPropagation();e.preventDefault();beginAnnDrag(e,a,'resize')}}/></div>:<svg key={a.id} className="penAnn" viewBox="0 0 1 1" preserveAspectRatio="none"><polyline points={(a.points||[]).map(p=>p.x+','+p.y).join(' ')} style={{stroke:a.color||'#2563eb'}} /></svg>)}
  {regionDraft&&<div className="regionDraft" style={{left:regionDraft.x*100+'%',top:regionDraft.y*100+'%',width:regionDraft.w*100+'%',height:regionDraft.h*100+'%',background:occlusionFill,borderColor:occlusionBorder,opacity:occlusionOpacity}}/>}{drawing.length>1&&<svg className="penAnn"><polyline points={drawing.map(p=>p.x+','+p.y).join(' ')} style={{stroke:penColor}}/></svg>}{textDraft&&<input autoFocus className="inlineTextInput" style={{left:textDraft.x*100+'%',top:textDraft.y*100+'%',color:penColor}} value={textDraft.value} onChange={e=>setTextDraft({...textDraft,value:e.target.value})} onKeyDown={e=>{if(e.key==='Enter')void saveText();if(e.key==='Escape')setTextDraft(null)}} onPointerDown={e=>e.stopPropagation()} onBlur={()=>void saveText()} placeholder="Type text…"/>}
 </div><aside className="editorAside"><div className="toolHelp"><b>Editing tools</b><p><b>Occlusion:</b> drag the box to move it; drag the corner to resize it.</p><p><b>Pen:</b> draw anywhere.</p><p><b>Text:</b> select Text, then click the image.</p><p><b>Image:</b> add another image, then drag/resize it.</p></div><button onClick={()=>{setTool('region');setMessage('Double-click/tap and drag on the image to draw a new occlusion.')}}>Draw Occlusion</button><div className="occlusionControls"><label>Inside <input type="color" value={occlusionFill} onChange={e=>setOcclusionFill(e.target.value)}/></label><label>Border <input type="color" value={occlusionBorder} onChange={e=>setOcclusionBorder(e.target.value)}/></label><label>Transparency <input type="range" min="0.05" max="1" step="0.05" value={occlusionOpacity} onChange={e=>setOcclusionOpacity(Number(e.target.value))}/><span>{Math.round(occlusionOpacity*100)}%</span></label></div>{rs.map(r=><label className="region" key={r.id}><input type="checkbox" checked={selected.includes(r.id)} onChange={()=>setSelected(s=>s.includes(r.id)?s.filter(x=>x!==r.id):[...s,r.id])}/>{r.label||'Unnamed region'}<button onClick={()=>{del('regions',r.id);setRegions(s=>s.filter(x=>x.id!==r.id));setSelected(s=>s.filter(x=>x!==r.id))}}>×</button></label>)}<input value={deck} onChange={e=>setDeck(e.target.value)} placeholder="Deck"/><button disabled={!selected.length} onClick={saveCards}>Create Card from Selected</button><button onClick={()=>setSelected(rs.map(r=>r.id))}>Select All Occlusions</button><button onClick={()=>{setEditing(null);setTab('Dashboard')}}>Done</button></aside></div></section>}

 return <div className="app"><header><b>RecallForge</b><nav>{['Dashboard','Study','Editor','Browse','Settings'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav><button onClick={()=>fileRef.current?.click()}>+ Image</button><input ref={fileRef} hidden type="file" accept="image/*,.heic,.heif" onClick={e=>e.stopPropagation()} onChange={e=>{const f=e.currentTarget.files?.[0];e.currentTarget.value='';if(f)upload(f)}}/></header><main>
 {tab==='Dashboard'&&<section><h1>Today's Study</h1><div className="stats"><button className="statCard" onClick={()=>setTab('Browse')}><b>{cards.length}<small>Total cards</small></b></button><button className="statCard" onClick={()=>startStudy(false)}><b>{due.length}<small>Due now</small></b></button><button className="statCard" onClick={openImages}><b>{images.length}<small>Images</small></b></button></div><button className="primary" onClick={()=>startStudy(false)}>Start Review</button>{message&&<p className="message">{message}</p>}<h2>Workflow</h2><div className="workflow"><button onClick={()=>fileRef.current?.click()}>1. Upload image</button><button onClick={openImages}>2. Edit image / occlusions</button><button onClick={()=>setTab('Browse')}>3. Create and manage cards</button><button onClick={()=>startStudy(false)}>4. Recall</button><button onClick={()=>{setTab('Study');setHidden(false);setReviewAll(true);setIdx(0)}}>5. Reveal</button><button onClick={()=>startStudy(false)}>6. Review and rate</button></div></section>}
 {tab==='Study'&&<section><div className="sectionHead"><div><h2>Study</h2><p className="muted">{reviewAll?'Reviewing all cards':'Reviewing due cards'}</p></div></div>{!card?<div><p>{cards.length?'There are no cards due right now.':'No cards have been created yet.'}</p>{cards.length>0&&<button className="primary" onClick={()=>startStudy(true)}>Review all cards</button>}{images.length>0&&cards.length===0&&<button onClick={openImages}>Open image library</button>}</div>:<><div className="study"><img src={studyUrl} alt={studyImg?.name||'Study image'}/>{regions.filter(r=>card.regions.includes(r.id)).map(r=><div key={r.id} className={'studyMask '+(!hidden?'revealed':'')} style={{left:r.x*100+'%',top:r.y*100+'%',width:r.w*100+'%',height:r.h*100+'%'}} onClick={()=>setHidden(false)}>{hidden?'?':''}</div>)}</div><div className="controls"><button onClick={()=>setHidden(false)}>Show Answer</button><button onClick={()=>setHidden(false)}>Reveal All</button></div>{!hidden&&<div className="ratings">{[['Again',1],['Hard',2],['Good',3],['Easy',4]].map(([t,n])=><button key={String(t)} onClick={()=>rate(n as number)}>{t}</button>)}</div>}</>}</section>}
 {tab==='Editor'&&<Editor/>}
 {tab==='Browse'&&<section><h2>Browse</h2>{cards.length===0?<p>No cards yet.</p>:cards.map(c=><div className="row" key={c.id}><span>{c.deck}</span><span>{c.regions.length} occlusion(s)</span><span>{c.reps} reviews</span><button onClick={()=>{const i=images.find(x=>x.id===c.imageId);if(i){setEditing(i);setSelected(c.regions);setTab('Editor')}}}>Edit</button></div>)}</section>}
 {tab==='Settings'&&<section><h2>Data</h2><button onClick={backup}>Export complete backup</button><label className="filebtn">Restore backup<input type="file" accept=".json" onChange={e=>e.target.files?.[0]&&restore(e.target.files[0])}/></label><p>Cards and images are stored locally in IndexedDB. Nothing is sent to a server.</p></section>}
 </main></div>}
export default App;