import React,{useEffect,useMemo,useRef,useState}from'react';
type Region={id:string,imageId:string,x:number,y:number,w:number,h:number,label:string};type Img={id:string,blob:Blob,w:number,h:number,name:string};type Card={id:string,imageId:string,regions:string[],deck:string,tags:string[],due:number,reps:number,lapses:number,interval:number,ease:number};
const DB='recallforge-v1',V=1;let dbp:Promise<IDBDatabase>|null=null;
function db(){if(dbp)return dbp;dbp=new Promise((res,rej)=>{const r=indexedDB.open(DB,V);r.onupgradeneeded=()=>{const d=r.result;for(const n of['images','regions','cards'])if(!d.objectStoreNames.contains(n))d.createObjectStore(n,{keyPath:'id'});};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});return dbp}
async function all<T>(s:string){const d=await db(),t=d.transaction(s,'readonly').objectStore(s);return new Promise<T[]>((res,rej)=>{const r=t.getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function put(s:string,v:any){const d=await db();return new Promise<void>((res,rej)=>{const r=d.transaction(s,'readwrite').objectStore(s).put(v);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function del(s:string,id:string){const d=await db();d.transaction(s,'readwrite').objectStore(s).delete(id)}
const uid=()=>crypto.randomUUID(),now=()=>Date.now();
const blobUrl=(b?:Blob)=>b?URL.createObjectURL(b):'';

function ImageThumb({image,onOpen}:{image:Img;onOpen:()=>void}){const[u,setU]=useState('');useEffect(()=>{const x=blobUrl(image.blob);setU(x);return()=>URL.revokeObjectURL(x)},[image]);return <div className="imageCard"><img src={u} alt={image.name}/><div className="imageMeta"><b title={image.name}>{image.name}</b><small>{image.w} × {image.h}px</small><button onClick={onOpen}>Open in Editor</button></div></div>}

function App(){
 const[tab,setTab]=useState('Dashboard'),[images,setImages]=useState<Img[]>([]),[regions,setRegions]=useState<Region[]>([]),[cards,setCards]=useState<Card[]>([]),[deck,setDeck]=useState('Default'),[selected,setSelected]=useState<string[]>([]),[editing,setEditing]=useState<Img|null>(null),[editingUrl,setEditingUrl]=useState(''),[studyUrl,setStudyUrl]=useState(''),[hidden,setHidden]=useState(true),[idx,setIdx]=useState(0),[reviewAll,setReviewAll]=useState(false),[message,setMessage]=useState('');
 const fileRef=useRef<HTMLInputElement>(null);
 async function refresh(){setImages(await all<Img>('images'));setRegions(await all<Region>('regions'));setCards(await all<Card>('cards'))}
 useEffect(()=>{refresh()},[]);
 const due=useMemo(()=>cards.filter(c=>c.due<=now()),[cards]),queue=reviewAll?cards:due,card=queue.length?queue[idx%queue.length]:undefined;
 const studyImg=card?images.find(x=>x.id===card.imageId):undefined;
 useEffect(()=>{if(!editing){setEditingUrl('');return}const u=blobUrl(editing.blob);setEditingUrl(u);return()=>URL.revokeObjectURL(u)},[editing]);
 useEffect(()=>{if(!studyImg){setStudyUrl('');return}const u=blobUrl(studyImg.blob);setStudyUrl(u);return()=>URL.revokeObjectURL(u)},[studyImg]);
 async function upload(f:File){if(!f.type.startsWith('image/'))return;const u=URL.createObjectURL(f),im=new Image();im.src=u;await new Promise((r,j)=>{im.onload=r;im.onerror=j});URL.revokeObjectURL(u);const x:Img={id:uid(),blob:f,w:im.naturalWidth,h:im.naturalHeight,name:f.name};await put('images',x);await refresh();setEditing(x);setSelected([]);setTab('Editor');setMessage('Image uploaded — draw hidden regions to create a card.')}
 function openImage(i:Img){setEditing(i);setSelected([]);setTab('Editor')}
 function openImages(){setEditing(null);setSelected([]);setTab('Editor')}
 function addRegion(){if(!editing)return;const r:Region={id:uid(),imageId:editing.id,x:.2,y:.2,w:.25,h:.12,label:''};put('regions',r).then(()=>{setRegions(x=>[...x,r]);setSelected([r.id])})}
 async function saveCards(){if(!editing||!selected.length)return;const c:Card={id:uid(),imageId:editing.id,regions:selected,deck,tags:[],due:now(),reps:0,lapses:0,interval:0,ease:2.5};await put('cards',c);setMessage('Card created');setTab('Dashboard');setIdx(0);setHidden(true);setReviewAll(false);await refresh()}
 async function rate(n:number){if(!card)return;const c={...card,reps:card.reps+1};if(n===1){c.lapses++;c.interval=0;c.ease=Math.max(1.3,c.ease-.2);c.due=now()+60000}else{const mult=n===2?0.7:n===3?c.ease:c.ease+0.25;c.interval=Math.max(1,Math.round((c.interval||1)*mult));c.ease=Math.max(1.3,c.ease+(n===2?-.15:n===4?.15:0));c.due=now()+c.interval*86400000}await put('cards',c);setHidden(true);setIdx(x=>x+1);await refresh()}
 function startStudy(allCards=false){setReviewAll(allCards);setIdx(0);setHidden(true);setTab('Study')}
 async function backup(){const dataUrl=async(b:Blob)=>new Promise<string>((r,j)=>{const x=new FileReader();x.onload=()=>r(String(x.result));x.onerror=()=>j(x.error);x.readAsDataURL(b)});const ims=await Promise.all(images.map(async x=>({...x,blob:await dataUrl(x.blob)})));const rs=await all<Region>('regions');const b={version:1,images:ims,regions:rs,cards};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(b)],{type:'application/json'}));a.download='recallforge-backup.json';a.click()}
 async function restore(f:File){const b=JSON.parse(await f.text());for(const x of b.images){const blob=await(await fetch(x.blob)).blob();await put('images',{...x,blob})}for(const r of b.regions)await put('regions',r);for(const c of b.cards)await put('cards',c);await refresh();setMessage('Backup restored')}
 function Editor(){const rs=regions.filter(r=>r.imageId===editing?.id);if(!editing)return <section><div className="sectionHead"><div><h2>Image Library</h2><p className="muted">Your uploaded images are stored locally on this device.</p></div><button onClick={()=>fileRef.current?.click()}>+ Upload Image</button></div>{images.length===0?<p>No images uploaded yet.</p>:<div className="imageGrid">{images.map(i=><ImageThumb key={i.id} image={i} onOpen={()=>openImage(i)}/>)}</div>}</section>;return <section><div className="sectionHead"><div><h2>Image Occlusion Editor</h2><p className="muted">{editing.name} · {editing.w} × {editing.h}px</p></div><button onClick={openImages}>Back to Images</button></div><div className="editor"><div className="canvas"><img src={editingUrl} alt={editing.name}/>{rs.map(r=><div key={r.id} className={'mask '+(selected.includes(r.id)?'sel':'')} style={{left:r.x*100+'%',top:r.y*100+'%',width:r.w*100+'%',height:r.h*100+'%'}} onClick={()=>setSelected(s=>s.includes(r.id)?s.filter(x=>x!==r.id):[...s,r.id])}>{r.label||'Region'}</div>)}</div><aside><button onClick={addRegion}>+ Add Region</button>{rs.map(r=><label className="region" key={r.id}><input type="checkbox" checked={selected.includes(r.id)} onChange={()=>setSelected(s=>s.includes(r.id)?s.filter(x=>x!==r.id):[...s,r.id])}/>{r.label||'Unnamed region'}<button onClick={()=>{del('regions',r.id);setRegions(s=>s.filter(x=>x.id!==r.id));setSelected(s=>s.filter(x=>x!==r.id))}}>×</button></label>)}<input value={deck} onChange={e=>setDeck(e.target.value)} placeholder="Deck"/><button disabled={!selected.length} onClick={saveCards}>Create Card from Selected</button><button onClick={()=>setSelected(rs.map(r=>r.id))}>Select All</button><button onClick={()=>{setEditing(null);setTab('Dashboard')}}>Done</button></aside></div></section>}
 return <div className="app"><header><b>RecallForge</b><nav>{['Dashboard','Study','Editor','Browse','Settings'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav><button onClick={()=>fileRef.current?.click()}>+ Image</button><input ref={fileRef} hidden type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></header><main>
 {tab==='Dashboard'&&<section><h1>Today's Study</h1><div className="stats"><button className="statCard" onClick={()=>setTab('Browse')}><b>{cards.length}<small>Total cards</small></b></button><button className="statCard" onClick={()=>startStudy(false)}><b>{due.length}<small>Due now</small></b></button><button className="statCard" onClick={openImages}><b>{images.length}<small>Images</small></b></button></div><button className="primary" onClick={()=>startStudy(false)}>Start Review</button>{message&&<p className="message">{message}</p>}<h2>Workflow</h2><div className="workflow"><button onClick={()=>fileRef.current?.click()}>1. Upload image</button><button onClick={openImages}>2. Draw/select hidden regions</button><button onClick={()=>setTab('Browse')}>3. Create and manage cards</button><button onClick={()=>startStudy(false)}>4. Recall</button><button onClick={()=>{setTab('Study');setHidden(false);setReviewAll(true);setIdx(0)}}>5. Reveal</button><button onClick={()=>startStudy(false)}>6. Review and rate</button></div></section>}
 {tab==='Study'&&<section><div className="sectionHead"><div><h2>Study</h2><p className="muted">{reviewAll?'Reviewing all cards':'Reviewing due cards'}</p></div></div>{!card?<div><p>{cards.length?'There are no cards due right now.':'No cards have been created yet.'}</p>{cards.length>0&&<button className="primary" onClick={()=>startStudy(true)}>Review all cards</button>}{images.length>0&&cards.length===0&&<button onClick={openImages}>Open image library</button>}</div>:<><div className="study"><img src={studyUrl} alt={studyImg?.name||'Study image'}/>{regions.filter(r=>card.regions.includes(r.id)).map(r=><div key={r.id} className={'studyMask '+(!hidden?'revealed':'')} style={{left:r.x*100+'%',top:r.y*100+'%',width:r.w*100+'%',height:r.h*100+'%'}} onClick={()=>setHidden(false)}>{hidden?'?':''}</div>)}</div><div className="controls"><button onClick={()=>setHidden(false)}>Show Answer</button><button onClick={()=>setHidden(false)}>Reveal All</button></div>{!hidden&&<div className="ratings">{[['Again',1],['Hard',2],['Good',3],['Easy',4]].map(([t,n])=><button key={String(t)} onClick={()=>rate(n as number)}>{t}</button>)}</div>}</>}</section>}
 {tab==='Editor'&&<Editor/>}
 {tab==='Browse'&&<section><h2>Browse</h2>{cards.length===0?<p>No cards yet.</p>:cards.map(c=><div className="row" key={c.id}><span>{c.deck}</span><span>{c.regions.length} occlusion(s)</span><span>{c.reps} reviews</span><button onClick={()=>{const i=images.find(x=>x.id===c.imageId);if(i){setEditing(i);setSelected(c.regions);setTab('Editor')}}}>Edit</button></div>)}</section>}
 {tab==='Settings'&&<section><h2>Data</h2><button onClick={backup}>Export complete backup</button><label className="filebtn">Restore backup<input type="file" accept=".json" onChange={e=>e.target.files?.[0]&&restore(e.target.files[0])}/></label><p>Cards and images are stored locally in IndexedDB. Nothing is sent to a server.</p></section>}
 </main></div>}
export default App;