import React,{useEffect,useMemo,useRef,useState}from'react';
type Region={id:string,x:number,y:number,w:number,h:number,label:string};type Img={id:string,blob:Blob,w:number,h:number,name:string};type Card={id:string,imageId:string,regions:string[],deck:string,tags:string[],due:number,reps:number,lapses:number,interval:number,ease:number};
const DB='recallforge-v1',V=1;let dbp:Promise<IDBDatabase>|null=null;
function db(){if(dbp)return dbp;dbp=new Promise((res,rej)=>{const r=indexedDB.open(DB,V);r.onupgradeneeded=()=>{const d=r.result;for(const n of['images','regions','cards'])if(!d.objectStoreNames.contains(n))d.createObjectStore(n,{keyPath:'id'});};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});return dbp}
async function all<T>(s:string){const d=await db(),t=d.transaction(s,'readonly').objectStore(s);return new Promise<T[]>((res,rej)=>{const r=t.getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function put(s:string,v:any){const d=await db();return new Promise<void>((res,rej)=>{const r=d.transaction(s,'readwrite').objectStore(s).put(v);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function del(s:string,id:string){const d=await db();d.transaction(s,'readwrite').objectStore(s).delete(id)}
const uid=()=>crypto.randomUUID();const now=()=>Date.now();const dataUrl=(b:Blob)=>new Promise<string>((r,j)=>{const x=new FileReader();x.onload=()=>r(String(x.result));x.onerror=()=>j(x.error);x.readAsDataURL(b)});
function App(){const[tab,setTab]=useState('Dashboard'),[images,setImages]=useState<Img[]>([]),[regions,setRegions]=useState<Region[]>([]),[cards,setCards]=useState<Card[]>([]),[deck,setDeck]=useState('Default'),[selected,setSelected]=useState<string[]>([]),[editing,setEditing]=useState<Img|null>(null),[url,setUrl]=useState(''),[hidden,setHidden]=useState(true),[idx,setIdx]=useState(0),[message,setMessage]=useState('');const fileRef=useRef<HTMLInputElement>(null);
async function refresh(){setImages(await all<Img>('images'));setRegions(await all<Region>('regions'));setCards(await all<Card>('cards'))}useEffect(()=>{refresh()},[]);
const due=useMemo(()=>cards.filter(c=>c.due<=now()),[cards]);const card=due[idx%due.length];const img=card&&images.find(x=>x.id===card.imageId);
useEffect(()=>{if(img){const u=URL.createObjectURL(img.blob);setUrl(u);return()=>URL.revokeObjectURL(u)}setUrl('')},[img]);
async function upload(f:File){if(!f.type.startsWith('image/'))return;const im=new Image();im.src=URL.createObjectURL(f);await new Promise(r=>im.onload=r);const x={id:uid(),blob:f,w:im.naturalWidth,h:im.naturalHeight,name:f.name};await put('images',x);setEditing(x);setTab('Editor');refresh()}
function addRegion(){if(!editing)return;const r={id:uid(),x:.2,y:.2,w:.25,h:.12,label:''};put('regions',{...r,imageId:editing.id}).then(()=>{setRegions(x=>[...x,r]);setSelected([r.id])})}
async function saveCards(){if(!editing||!selected.length)return;const c:Card={id:uid(),imageId:editing.id,regions:selected,deck,tags:[],due:now(),reps:0,lapses:0,interval:0,ease:2.5};await put('cards',c);setMessage('Card created');setTab('Dashboard');refresh()}
async function rate(n:number){if(!card)return;const c={...card,reps:card.reps+1};if(n===1){c.lapses++;c.interval=0;c.ease=Math.max(1.3,c.ease-.2);c.due=now()+60000}else{const mult=n===2?.7:n===3?c.ease: c.ease+0.25;c.interval=Math.max(1,Math.round((c.interval||1)*mult));c.ease=Math.max(1.3,c.ease+(n===2?-.15:n===4?.15:0));c.due=now()+c.interval*86400000}await put('cards',c);setHidden(true);setIdx(x=>x+1);refresh()}
async function backup(){const ims=await Promise.all(images.map(async x=>({...x,blob:await dataUrl(x.blob)})));const rs=await all<any>('regions');const b={version:1,images:ims,regions:rs,cards};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(b)],{type:'application/json'}));a.download='recallforge-backup.json';a.click()}
async function restore(f:File){const b=JSON.parse(await f.text());for(const x of b.images){const blob=await (await fetch(x.blob)).blob();await put('images',{...x,blob})}for(const r of b.regions)await put('regions',r);for(const c of b.cards)await put('cards',c);refresh();setMessage('Backup restored')}
function Editor(){const rs=regions.filter((r:any)=>r.imageId===editing?.id);return <section><h2>Image Occlusion Editor</h2><div className="editor"><div className="canvas"><img src={url}/>{rs.map((r:any)=><div key={r.id} className={'mask '+(selected.includes(r.id)?'sel':'')} style={{left:r.x*100+'%',top:r.y*100+'%',width:r.w*100+'%',height:r.h*100+'%'}} onClick={()=>setSelected(s=>s.includes(r.id)?s.filter(x=>x!==r.id):[...s,r.id])}>{r.label||'Region'}</div>)}</div><aside><button onClick={addRegion}>+ Add Region</button>{rs.map((r:any)=><label className="region" key={r.id}><input type="checkbox" checked={selected.includes(r.id)} onChange={()=>setSelected(s=>s.includes(r.id)?s.filter(x=>x!==r.id):[...s,r.id])}/>{r.label||'Unnamed region'}<button onClick={()=>{del('regions',r.id);setRegions(s=>s.filter(x=>x.id!==r.id));setSelected(s=>s.filter(x=>x!==r.id))}}>×</button></label>)}<input value={deck} onChange={e=>setDeck(e.target.value)} placeholder="Deck"/><button disabled={!selected.length} onClick={saveCards}>Create Card from Selected</button><button onClick={()=>setSelected(rs.map(r=>r.id))}>Select All</button><button onClick={()=>{setEditing(null);setTab('Dashboard')}}>Done</button></aside></div></section>}
return <div className="app"><header><b>RecallForge</b><nav>{['Dashboard','Study','Editor','Browse','Settings'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav><button onClick={()=>fileRef.current?.click()}>+ Image</button><input ref={fileRef} hidden type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></header><main>{tab==='Dashboard'&&<section><h1>Today's Study</h1><div className="stats"><b>{cards.length}<small>Total cards</small></b><b>{due.length}<small>Due now</small></b><b>{images.length}<small>Images</small></b></div><button className="primary" onClick={()=>setTab('Study')}>Start Review</button>{message&&<p>{message}</p>}<h2>Workflow</h2><p>Upload → draw/select hidden regions → create cards → recall → reveal → rate.</p></section>}{tab==='Study'&&<section><h2>Study</h2>{!card?<p>No cards are due.</p>:<><div className="study"><img src={url}/>{regions.filter((r:any)=>card.regions.includes(r.id)).map((r:any)=><div className={'studyMask '+(!hidden?'revealed':'')} style={{left:r.x*100+'%',top:r.y*100+'%',width:r.w*100+'%',height:r.h*100+'%'}} onClick={()=>setHidden(false)}>{hidden?'?':''}</div>)}</div><div className="controls"><button onClick={()=>setHidden(false)}>Show Answer</button><button onClick={()=>setHidden(false)}>Reveal All</button></div>{!hidden&&<div className="ratings">{[['Again',1],['Hard',2],['Good',3],['Easy',4]].map(([t,n])=><button onClick={()=>rate(n as number)}>{t}</button>)}</div>}</>}</section>}{tab==='Editor'&&editing?<Editor/>:null}{tab==='Browse'&&<section><h2>Browse</h2>{cards.map(c=><div className="row"><span>{c.deck}</span><span>{c.regions.length} occlusion(s)</span><span>{c.reps} reviews</span><button onClick={()=>{const i=images.find(x=>x.id===c.imageId);if(i){setEditing(i);setSelected(c.regions);setTab('Editor')}}}>Edit</button></div>)}</section>}{tab==='Settings'&&<section><h2>Data</h2><button onClick={backup}>Export complete backup</button><label className="filebtn">Restore backup<input type="file" accept=".json" onChange={e=>e.target.files?.[0]&&restore(e.target.files[0])}/></label><p>Cards and images are stored locally in IndexedDB. Nothing is sent to a server.</p></section>}</main></div>}
export default App;