import React,{useEffect,useState}from'react';
import{createUserWithEmailAndPassword,GoogleAuthProvider,onAuthStateChanged,reauthenticateWithPopup,sendPasswordResetEmail,signInWithEmailAndPassword,signInWithPopup,signOut,updateProfile,type User}from'firebase/auth';
import{auth}from'./firebase';import{connectDrive,disconnectDrive,syncToDrive}from'./drive';

type Mode='signin'|'signup'|'forgot';

function ensureStore(db:IDBDatabase,name:string){if(!db.objectStoreNames.contains(name))db.createObjectStore(name,{keyPath:'id'});}
async function openDb(name:string){return new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open(name,3);r.onupgradeneeded=()=>{const d=r.result;for(const n of['images','regions','cards','annotations','folders'])ensureStore(d,n)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function copyStore(source:IDBDatabase,target:IDBDatabase,name:string){return new Promise<void>((resolve,reject)=>{const r=source.transaction(name,'readonly').objectStore(name).getAll();r.onsuccess=()=>{try{const tx=target.transaction(name,'readwrite');for(const item of r.result)tx.objectStore(name).put(item);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)}catch(e){reject(e)}};r.onerror=()=>reject(r.error)})}
async function migrateLegacyData(uid:string){const flag=`rf-migrated-${uid}`;if(localStorage.getItem(flag))return;const source=await openDb('recallforge-v1');const target=await openDb(`recallforge-v1-${uid}`);for(const n of['images','regions','cards','annotations','folders'])await copyStore(source,target,n);source.close();target.close();localStorage.setItem(flag,'1');}

function provider(){const p=new GoogleAuthProvider();p.addScope('https://www.googleapis.com/auth/drive.file');p.setCustomParameters({prompt:'consent'});return p;}
async function connectForUser(user:User){const result=await reauthenticateWithPopup(user,provider());const credential=GoogleAuthProvider.credentialFromResult(result);const token=credential?.accessToken;const googleEmail=result.user.email?.toLowerCase();if(!token)throw new Error('Google did not return Drive authorization.');if(googleEmail&&user.email&&googleEmail!==user.email.toLowerCase())throw new Error('Choose the same Google account as your RecallForge email.');await connectDrive(token);await syncToDrive();}

function AuthShell({children}:{children:React.ReactNode}){
 const[mode,setMode]=useState<Mode>('signin'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[user,setUser]=useState<User|null>(null),[driveReady,setDriveReady]=useState(false),[driveBusy,setDriveBusy]=useState(false);
 useEffect(()=>onAuthStateChanged(auth,async next=>{setUser(next);if(next){await migrateLegacyData(next.uid);localStorage.setItem('rf-active-user',next.uid)}else{localStorage.removeItem('rf-active-user');setDriveReady(false);disconnectDrive()}}),[]);
 useEffect(()=>{const handler=()=>{if(!driveReady)return;window.clearTimeout((window as any).__rfSyncTimer);(window as any).__rfSyncTimer=window.setTimeout(()=>{void syncToDrive().catch(e=>setMessage(e instanceof Error?e.message:'Could not save to Google Drive.'))},1200)};window.addEventListener('recallforge-data-changed',handler);return()=>window.removeEventListener('recallforge-data-changed',handler)},[driveReady]);
 const submit=async()=>{setMessage('');setBusy(true);try{if(!email.trim())throw new Error('Enter your email address.');if(mode==='forgot'){await sendPasswordResetEmail(auth,email.trim());setMessage('Password reset email sent. Check your inbox.')}else if(mode==='signup'){if(password.length<6)throw new Error('Password must be at least 6 characters.');if(password!==confirm)throw new Error('Passwords do not match.');const r=await createUserWithEmailAndPassword(auth,email.trim(),password);await updateProfile(r.user,{displayName:email.trim().split('@')[0]})}else await signInWithEmailAndPassword(auth,email.trim(),password)}catch(e:any){if(e?.code==='auth/email-already-in-use'){setMessage('This email is already registered. Please sign in.');setMode('signin')}else if(e?.code==='auth/invalid-credential'||e?.code==='auth/wrong-password')setMessage('Incorrect email or password.');else setMessage(e?.message||'Authentication failed.')}finally{setBusy(false)}};
 const google=async()=>{setMessage('');setBusy(true);try{const r=await signInWithPopup(auth,provider());const c=GoogleAuthProvider.credentialFromResult(r);if(!c?.accessToken)throw new Error('Google sign-in succeeded, but Drive authorization was not returned.');await connectDrive(c.accessToken);await syncToDrive();setDriveReady(true)}catch(e:any){setMessage(e?.message||'Google sign-in failed.')}finally{setBusy(false)}};
 const connect=async()=>{if(!user)return;setDriveBusy(true);setMessage('');try{await connectForUser(user);setDriveReady(true)}catch(e:any){setMessage(e?.message||'Could not connect Google Drive.')}finally{setDriveBusy(false)}};
 const logout=async()=>{await signOut(auth);localStorage.removeItem('rf-active-user');disconnectDrive()};
 if(!user)return <div className="authPage"><div className="authCard"><div className="authBrand">RecallForge</div><h1>{mode==='signup'?'Create your account':mode==='forgot'?'Reset your password':'Welcome back'}</h1><p className="authSubtitle">{mode==='forgot'?'Enter your registered email and we will send a secure reset link.':'Your flashcards and study workspace, available across your devices.'}</p>{mode!=='forgot'&&<button className="googleButton" onClick={()=>void google()} disabled={busy}>Continue with Google</button>}{mode!=='forgot'&&<div className="authDivider"><span>or</span></div>}<label>Email<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label>{mode!=='forgot'&&<label>Password<input type="password" autoComplete={mode==='signup'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••"/></label>}{mode==='signup'&&<label>Confirm password<input type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="••••••••"/></label>}{message&&<div className="authMessage">{message}</div>}<button className="primary authSubmit" onClick={()=>void submit()} disabled={busy}>{mode==='signup'?'Create account':mode==='forgot'?'Send reset email':'Sign in'}</button>{mode==='signin'&&<button className="authLink" onClick={()=>{setMode('forgot');setMessage('')}}>Forgot password?</button>}{mode!=='signup'?<p className="authSwitch">New to RecallForge? <button onClick={()=>{setMode('signup');setMessage('')}}>Create account</button></p>:<p className="authSwitch">Already registered? <button onClick={()=>{setMode('signin');setMessage('')}}>Sign in</button></p>}</div></div>;
 if(!driveReady)return <div className="authPage"><div className="authCard driveCard"><div className="authBrand">RecallForge</div><h1>Connect Google Drive</h1><p className="authSubtitle">RecallForge stores your workspace in your own Google Drive so your data follows your account.</p><div className="drivePrivacy"><b>What RecallForge will access</b><p>Only files created by RecallForge through Google's <code>drive.file</code> permission. It does not scan your personal Drive or read unrelated files.</p><b>What it will do</b><p>Create a dedicated <b>RecallForge</b> folder and save your flashcards, images, topics, editor data, and study data there.</p><b>What it will not do</b><p>It will not browse, modify, or delete unrelated personal Drive files.</p></div>{message&&<div className="authMessage">{message}</div>}<button className="primary authSubmit" onClick={()=>void connect()} disabled={driveBusy}>{driveBusy?'Connecting…':'Connect Google Drive'}</button><button className="authLink" onClick={()=>void logout()}>Sign out</button></div></div>;
 return <>{React.cloneElement(children as React.ReactElement,{__authUser:user,__onSignOut:logout,__driveReady:driveReady})}</>;
}
export default function AuthGate({children}:{children:React.ReactNode}){return <AuthShell>{children}</AuthShell>}